# 22 february 2016

---
#Filtering:
#  type: butterworth
#  order: 8
#  frequency: 10000

Indices:

  Acoustic_Complexity_Index:
    function: compute_ACI
    spectro:
      windowLength: 512
      windowHop: 512
      scale_audio: False
      square: False
      windowType: hamming
      centered: False
      normalized: True
    arguments:
      j_bin: 5 # j_bin in seconds

  Acoustic_Diversity_Index:
    function: compute_ADI
    arguments:
      max_freq: 10000
      db_threshold: -50
      freq_step: 1000

  Normalized_Difference_Sound_Index:
    function: compute_NDSI
    arguments:
      windowLength: 1024
      anthrophony: [1000,2000]
      biophony: [2000,11000]

...
