# R Docker

FROM ubuntu:24.04

ARG r_version=4.5.3

ENV DEBIAN_FRONTEND=noninteractive

# Install base system and devel tools
RUN \
  sed -i 's/# \(.*multiverse$\)/\1/g' /etc/apt/sources.list && \
  apt-get update && \
  apt-get install -y apt-utils && \
  #apt-get -y upgrade && \
  apt-get install -y build-essential && \
  apt-get install -y software-properties-common && \
  apt-get install -y curl git htop man unzip vim wget && \
  apt-get install -y locales && \
  apt-get install -y libssl-dev libgit2-dev 

RUN echo "en_US.UTF-8 UTF-8" >> /etc/locale.gen && locale-gen en_US.utf8 && /usr/sbin/update-locale LANG=en_US.UTF-8

ENV LC_ALL en_US.UTF-8
ENV LANG en_US.UTF-8

#
# R external dependencies
#
RUN apt install -y openmpi-*
RUN apt install -y gfortran libreadline-dev xorg-dev libbz2-dev liblzma-dev libpcre3-dev libcurl4-openssl-dev
RUN apt install -y libtiff-dev libjpeg-dev libicu-dev libcairo-dev default-jdk tk8.6-dev libpcre2-dev libxml2-dev
RUN apt install -y cmake libfftw3-dev libgmp3-dev libfribidi-dev libharfbuzz-dev libglpk-dev

# for amt
RUN apt-get install -y libmagick++-dev

# for sf / stars
RUN apt-get install -y libudunits2-dev

# for rgdal 
RUN apt-get install -y libgdal-dev gdal-bin libproj-dev proj-data proj-bin libgeos-dev

# for rjags
RUN apt-get install -y jags

# for amt
RUN apt-get install -y libmpfr-dev; apt-get install -y libgsl-dev


# Compile and install an R in portable version
WORKDIR /tmp
RUN wget https://cran.r-project.org/src/base/R-4/R-${r_version}.tar.gz -O R-${r_version}.tar.gz

RUN tar zxf R-${r_version}.tar.gz
WORKDIR R-${r_version}
RUN ./configure --prefix=/opt/PortableR --enable-static=yes --enable-shared=yes --enable-R-shlib --with-tcltk

RUN make -j$(nproc); make install

WORKDIR /bin
RUN ln -s /opt/PortableR/bin/* .

WORKDIR /

#Setup CRAN mirror
COPY Rprofile.site /opt/PortableR/lib/R/etc


# Define default command.
CMD ["bash"]


# R package exceptions
COPY files/Boruta_8.0.0.tar.gz /

# install R packages

# install "pak" for installing all other packages

RUN R -e "p='pak'; install.packages(p, dependencies=TRUE, Ncpus=parallel::detectCores()); if (!library(p, character.only=TRUE, logical.return=T)) quit(status=10)"



RUN R -e "pak::pkg_install(c('ade4', 'adehabitatHR', 'agricolae', 'amt', 'apcluster', 'ape', 'assertthat', 'audio'), ask=FALSE)"

# RUN R -e "pak::pkg_install(c('', '', '', '', '', '', '', ''), ask=FALSE)"

RUN R -e "pak::pkg_install(c('bayesdfa', 'bindrcpp'), ask=FALSE)"

RUN R -e "pak::pkg_install(c('car', 'caret', 'caTools', 'class', 'clue',  'clustertend', 'clValid', 'coda', 'correctR',  'corrplot',  'crqa', 'ctv' ), ask=FALSE)"


RUN R -e "pak::pkg_install(c('dendextend', 'devtools', 'digest', 'diptest', 'doParallel', 'dplyr', 'dtw', 'dtwclust', 'dygraphs'), ask=FALSE)"

RUN R -e "pak::pkg_install(c('e1071', 'ellipse', 'exactextractr'), ask=FALSE)"

RUN R -e "pak::pkg_install(c('factoextra', 'FactoMineR', 'fasterize', 'FD', 'flexmix', 'fossil', 'foreach', 'fpc', 'fs', 'functional'), ask=FALSE)"

RUN R -e "pak::pkg_install(c('gdtools', 'geometry', 'ggplot2', 'ggpubr', 'ggrepel', 'ggthemes'), ask=FALSE)"

RUN R -e "pak::pkg_install(c('glmmTMB', 'glue', 'gmp', 'gridExtra', 'gtable', 'gtools'), ask=FALSE)"

RUN R -e "pak::pkg_install(c('jagsUI'), ask=FALSE)"

RUN R -e "pak::pkg_install(c('Hmsc', 'hopkins'), ask=FALSE)"

RUN R -e "pak::pkg_install(c('kernlab'), ask=FALSE)"

RUN R -e "pak::pkg_install(c('landscapemetrics', 'lattice', 'lazyeval', 'lubridate'), ask=FALSE)"

RUN R -e "pak::pkg_install(c('magrittr', 'MASS', 'matrixStats', 'mcclust', 'mclust', 'MCMCglmm', 'mcmcplots', 'MetBrewer', 'mgcv', 'mlbench', 'ModelMetrics', 'monitoR', 'move', 'moveHMM', 'multcompView', 'mvtnorm'), ask=FALSE)"

RUN R -e "pak::pkg_install(c('NbClust', 'ncdf4', 'nimble', 'nimbleSCR', 'nlme'), ask=FALSE)"

RUN R -e "pak::pkg_install(c('MuMIn'), ask=FALSE)"

RUN R -e "pak::pkg_install(c('OpenImageR', 'osmextract'), ask=FALSE)"

RUN R -e "pak::pkg_install(c('parallelDist', 'pdist', 'permute', 'pkgconfig', 'plyr', 'prabclus', 'purrr', 'pvclust', 'R2jags'), ask=FALSE)"

RUN R -e "pak::pkg_install(c('R6', 'randomForest', 'ranger', 'RANN', 'raster', 'rasterVis', 'Rcpp', 'RcppArmadillo', 'RcppCNPy', 'RcppProgress', 'rdist', 'readr', 'rgdal', 'reshape2', 'rlang', 'Rmisc', 'robustbase', 'ROCR', 'RSNNS', 'RSQLite', 'R.utils', 'runjags'), ask=FALSE)"

RUN R -e "pak::pkg_install(c('scales', 'seewave', 'sf', 'sjmisc', 'smacof', 'snow'), ask=FALSE)"

RUN R -e "pak::pkg_install(c('soundecology', 'soundgen', 'sp', 'spaa', 'splines2', 'stars', 'stringr'), ask=FALSE)"

RUN R -e "pak::pkg_install(c('tclust', 'tibble', 'tidymodels', 'tidyr', 'tidyverse', 'trimcluster', 'TSclust', 'TSdist', 'tuneR'), ask=FALSE)"

RUN R -e "pak::pkg_install(c('umap', 'unmarked', 'usdm'), ask=FALSE)"

RUN R -e "pak::pkg_install(c('vegan', 'vegclust', 'warbleR'), ask=FALSE)"

RUN R -e "pak::pkg_install(c('xts', ), ask=FALSE)"




# FROM GITHUB

#RUN bash /install_r_package_from_github.bash pimentel/cluster
#RUN bash /install_r_package_from_github.bash Cdevenish/hardRain

#RUN bash /install_r_package.bash local:Boruta_8.0.0.tar.gz Boruta

# FROM BIOCONDUCTOR
#RUN bash /install_r_package_from_bioconductor.bash phyloseq


# RUN Rscript /install_r_package.R PAMmisc SpaDES NetLogoR fastmatch grid fpCompare

#RUN R -q -e "install.packages('box', Ncpus=parallel::detectCores()); stopifnot(requireNamespace('box', quietly=TRUE))"



#RUN R -q -e 'pak::pkg_install(c("terra", "umap"), ask=FALSE)'


