#!/usr/bin/Rscript


# run Acoustic Complexity Index (ACI) from the Soundecology package

# version = '2'  # 2020-06-08


library("optparse")
library("soundecology")
library("tuneR")

option_list = list(

    make_option(c("-d", "--directory"), type="character", default=NULL, 
                help="Sounds directory path", metavar="character"),

    make_option(c("-o", "--output"), type="character", default="aci_out.tsv", 
                help="Output file name [default= %default]", metavar="character"),

    make_option(c("--min_freq"), type="integer", default=NA, 
                help="miminum frequency to use when calculating the value (default: NA)",
                metavar="number"),

    make_option(c("--max_freq"), type="integer", default=NA, 
                help="maximum frequency to use when calculating the value (default: NA)",
                metavar="number"),

    make_option(c("-f", "--fft_w"), type="integer", default=512, 
                help="FFT window to use (default: 512)",
                metavar="number"),

    make_option(c("-j", "--cluster_size"), type="integer", default=5, 
                help="Cluster size in seconds (default: 5)",
                metavar="number"),


    make_option(c("-c", "--cpu"), type="integer", default=1, 
                help="Number of cores to use", metavar="number")
); 
 
opt_parser = OptionParser(option_list=option_list);
opt = parse_args(opt_parser);

if (is.null(opt$directory)){
  print_help(opt_parser)
  stop("You must supply a directory", call.=FALSE)
}


multiple_sounds(directory=opt$directory,
                resultfile=opt$output,
                soundindex="acoustic_complexity",
                min_freq=opt$min_freq,
                max_freq=opt$max_freq,
                fft_w=opt$fft_w,
                j=opt$cluster_size,
                no_cores=opt$cpu)


