#!/usr/bin/Rscript


# Acoustic Richness

# read sounds directory as argument
# example: ar -d /home/sounds -o ar.tsv -c 2

library("optparse")
library("seewave")
library(tuneR)


option_list = list(

    make_option(c("-d", "--directory"), type="character", default=NULL, 
                help="sounds directory path", metavar="character"),

    make_option(c("-o", "--output"), type="character", default="ar_out.tsv", 
                help="output file name (full path must be specified) [default= %default]", metavar="character"),

    make_option(c("-e", "--envt"), type="character", default="hil", 
                help=" Type of envelope (default: hil)", metavar="character"),


#    make_option(c("-t", "--db_treshold"), type="integer", default=-50, 
#                help="Threshold to use in the calculation", metavar="number"),

#    make_option(c("-b", "--freq_step"), type="integer", default=1000, 
#                help="Size of frequency bands", metavar="number"),

#    make_option(c("-s", "--shannon"), type="logical", default=TRUE, 
#                help="Use the Shannon's diversity index to calculate the ADI", metavar="number"),

    make_option(c("-c", "--cpu"), type="integer", default=1, 
                help="Number of cores to use", metavar="number")
); 
 
opt_parser = OptionParser(option_list=option_list);
opt = parse_args(opt_parser);

if (is.null(opt$directory)){
  print_help(opt_parser)
  stop("You must supply a directory", call.=FALSE)
}

setwd(opt$directory)

arfile <- AR(opt$directory,
             datatype="files",
             envt=opt$envt,
             pattern = "\\.wav$|\\.WAV$")

write.table(arfile, file=opt$output, sep = "\t")

