#!/usr/bin/Rscript


# Normalized Difference Soundscape Index (NDSI)

# read sounds directory as argument
# example: ndsi -d /home/sounds -o ndsi.tsv -c 2

library("optparse")
library("soundecology")

option_list = list(

    make_option(c("-d", "--directory"), type="character", default=NULL, 
                help="sounds directory path", metavar="character"),

    make_option(c("-o", "--output"), type="character", default="ndsi_out.tsv", 
                help="output file name [default= %default]", metavar="character"),

    make_option(c("-f", "--fft_w"), type="integer", default=1024, 
                help="FFT window to use (default: 1024)",
                metavar="number"),

    make_option(c("--anthro_min"), type="integer", default=1000, 
                help="minimum value of the range of frequencies of the anthrophony (default: 1000)",
                metavar="number"),

    make_option(c("--anthro_max"), type="integer", default=2000, 
                help="maximum value of the range of frequencies of the anthrophony (default: 2000)",
                metavar="number"),

    make_option(c("--bio_min"), type="integer", default=2000, 
                help="minimum value of the range of frequencies of the biophony (default: 2000)",
                metavar="number"),

    make_option(c("--bio_max"), type="integer", default=11000, 
                help="maximum value of the range of frequencies of the biophony (default: 11000)",
                metavar="number"),

    make_option(c("-c", "--cpu"), type="integer", default=1, 
                help="Number of cores to use", metavar="number")
); 
 
opt_parser = OptionParser(option_list=option_list);
opt = parse_args(opt_parser);

if (is.null(opt$directory)){
  print_help(opt_parser)
  stop("You must supply a directory", call.=FALSE)
}


multiple_sounds(directory=opt$directory,
                resultfile=opt$output,
                soundindex="ndsi",
                fft_w=opt$fft_w,
                anthro_min=opt$anthro_min,
                anthro_max=opt$anthro_max,
                bio_min=opt$bio_min,
                bio_max=opt$bio_max,
                no_cores=opt$cpu)


